# global goal setting
global_goal:
  # swarm_central_pos: {x: 25.0, y: 0.0, z: 1.0}
  swarm_scale : 1.0
  relative_pos_0 : {x: 0.0, y: 0.0, z: 0.0}
  relative_pos_1 : {x: -2.5, y: 2.5, z: 0.0}
  relative_pos_2 : {x: -2.5, y: -2.5, z: 0.0}

uav_height: 3.0
distance_target: 3.0
distance_type: false  # false norm3D, true norm2D

wait_takeoff: false
wait_odom: true

path_number: -1  # if -1, all poses are considered

have_swarm_relative_pts_: true  # if false, the swarm will use the global goal position