# uav1:
#   id: 1
#   x: 5.0
#   y: 0.0
#   z: 0.0
#   heading: 0.0

# uav2:
#   id: 2
#   x: 2.5
#   y: 4.33
#   z: 0.0
#   heading: 0.0

# uav3:
#   id: 3
#   x: -2.5
#   y: 4.33
#   z: 0.0
#   heading: 0.0

# uav4:
#   id: 4
#   x: -5.0
#   y: 0.0
#   z: 0.0
#   heading: 0.0

# uav5:
#   id: 5
#   x: -2.5
#   y: -4.33
#   z: 0.0
#   heading: 0.0

# uav6:
#   id: 6
#   x: 2.5
#   y: -4.33
#   z: 0.0
#   heading: 0.0

# uav1:
#   id: 1
#   x: 15.0
#   y: 0.0
#   z: 0.0
#   heading: 0.0

# uav2:
#   id: 2
#   x: 12.5
#   y: 4.33
#   z: 0.0
#   heading: 0.0

# uav3:
#   id: 3
#   x: 7.5
#   y: 4.33
#   z: 0.0
#   heading: 0.0

# uav4:
#   id: 4
#   x: 5.0
#   y: 0.0
#   z: 0.0
#   heading: 0.0

# uav5:
#   id: 5
#   x: 7.5
#   y: -4.33
#   z: 0.0
#   heading: 0.0

# uav6:
#   id: 6
#   x: 12.5
#   y: -4.33
#   z: 0.0
#   heading: 0.0

uav1:
  id: 1
  x: 12.5
  y: 5.0
  z: 0.0
  heading: 0.0

uav2:
  id: 2
  x: 10.0
  y: 9.33
  z: 0.0
  heading: 0.0

uav3:
  id: 3
  x: 5.0
  y: 9.33
  z: 0.0
  heading: 0.0

uav4:
  id: 4
  x: 2.5
  y: 5.0
  z: 0.0
  heading: 0.0

uav5:
  id: 5
  x: 5.0
  y: 0.67
  z: 0.0
  heading: 0.0

uav6:
  id: 6
  x: 10.0
  y: 0.67
  z: 0.0
  heading: 0.0
