# the connecting root frame will be named like this
connecting_frame_id: "common_origin"

# these are the tf subtrees to be connected through the respective root frames so that the equal frames are equal
connections:
  - root_frame_id: "uav1/map_navsat"
    equal_frame_id: "uav1/liosam_origin"

  - root_frame_id: "uav2/map_navsat"
    equal_frame_id: "uav2/liosam_origin"

  - root_frame_id: "uav3/map_navsat"
    equal_frame_id: "uav3/liosam_origin"

  - root_frame_id: "uav4/map_navsat"
    equal_frame_id: "uav4/liosam_origin"

  - root_frame_id: "uav5/map_navsat"
    equal_frame_id: "uav5/liosam_origin"

  - root_frame_id: "uav6/map_navsat"
    equal_frame_id: "uav6/liosam_origin"

# if true, older messages than the last update of the respective frame connection will be ignored
ignore_older_messages: false

# if no update of a certain connection happens for this duration, it will be forced
max_update_period: 0.1 # seconds (set to zero to disable)
